# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: 7TV.Chatterino7
PackageVersion: 7.5.1
InstallerType: inno
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/SevenTV/chatterino7/releases/download/v7.5.1/Chatterino7.Installer.exe
  InstallerSha256: 3B6B60652C44E1567B3F5FC87A81EA885E5007206EFFC72278898BA8555AEC3A
ManifestType: installer
ManifestVersion: 1.6.0
